---

- name: copying file to server
  become: true 
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/
    owner: ubuntu
    group: ubuntu 
          
- name: "Extract artifact"
  become: true 
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/
    mode: 0777 
    remote_src: no
    owner: ubuntu
    group: ubuntu 
    
- name: "Install npm"
  become: true
  apt:
    name: ["npm"]
    state: present
    update_cache: yes 

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present 

- name: "start app"
  become: true 
  shell: |
      cd /artifact 
      npm install
      pm2 stop default
      pm2 start npm -- start

