---

- name: copying file with playbook
  become: true 
  copy:
    src: ~/project/tar -C backend -czvf artifact.tar.gz . 
    dest: ~/
    owner: ubuntu
    group: ubuntu        
- name: "Extract artifact"
  become: true 
  unarchive:
    src: ~/tar -C backend -czvf artifact.tar.gz .  
    dest: /var/www/
    mode: u+rx
- name: "Install npm"
  become: true
  apt:
    name: ["npm"]
    state: present
    update_cache: yes 
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present 
- name: "start app"
  become: true 
  shell: |
      pm2 stop default
      pm2 start npm -- start

