---

- name: copying file to server
  become: true 
  copy:
    src: ~/project/tar -C backend -czvf artifact.tar.gz . 
    dest: ~/
    owner: ubuntu
    group: ubuntu 
    mode: u+rx       
- name: "Extract artifact"
  become: true 
  unarchive:
    src: ~/
    dest: /var/www/html
    remote_src: yes
    
- name: "Install npm"
  become: true
  apt:
    name: ["npm"]
    state: present
    update_cache: yes 
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present 
- name: "start app"
  become: true 
  shell: |
      pm2 stop default
      pm2 start npm -- start

